apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb-internal
  annotations:
    # Set to "true" to make internal ALB the default for all Ingresses
    # ingressclass.kubernetes.io/is-default-class: "true"
spec:
  # Configures the IngressClass to use EKS Auto Mode
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb-internal
