# This file is templated by Terraform using templatefile()
# The following variables are substituted at deployment time:
#   ${subnet_ids} - JSON array of subnet IDs
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb-internal
spec:
  # Internal ALB - accessible only within VPC
  # Use for admin panels, internal APIs, microservices
  scheme: internal
  
  # Subnet selection - use explicit subnet IDs
  subnets:
    ids: ${subnet_ids}
